#Numpy-Pandas-Matplotlib-Seaborn  

## Numpy

In [ ]:
import numpy as np

In [ ]:
a=[1,3,5,"fatih","sueda",2j+5,3.5]

In [ ]:
a=[1,3,5,7,9]
b=[2,4,6,8,10]

In [ ]:
type(a)

list

In [ ]:
ab=[]
for i in range(len(a)):
  ab.append(a[i]*b[i])

ab

[2, 12, 30, 56, 90]

In [ ]:
x=np.array([1,3,5,7,9])
y=np.array(b)

In [ ]:
x*y

array([ 2, 12, 30, 56, 90])

In [ ]:
#0 > siyah
#1> beyaz

In [ ]:
sifirlar=np.zeros(10,dtype=int)
sifirlar

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
birler=np.ones(10,dtype=int)
birler

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
np.random.randint(5)

4

In [ ]:
np.random.randint(72,81)

77

In [ ]:
np.random.randint(1,81,100)

array([12, 62, 18, 37, 14, 68, 48, 73, 64,  2, 11, 38, 57, 75, 17,  1, 79,
       41,  2, 57, 59, 13, 45, 63, 68, 68, 74, 63, 54, 74, 25,  6, 25, 67,
        9, 25, 19, 23, 41, 22,  6, 22, 70, 71,  4, 12, 32, 21, 77, 79, 39,
       35, 73, 62,  9, 48, 63, 61, 18,  4, 39, 78, 62, 12, 60, 69, 32, 46,
       27, 34, 12, 32, 22, 44, 20,  4, 11, 17, 15, 28, 79, 55, 73, 28, 25,
       29, 36, 37, 16, 25, 56, 73, 27, 47, 39,  1, 74, 56, 39, 77])

In [ ]:
b=np.random.normal(10,4,(3,4))
b
# (3,4) MxN

array([[ 8.53023242, 11.21231296, 11.4152028 ,  6.47165557],
       [ 6.0367405 , 11.84628021,  8.38427478, 11.88785507],
       [ 9.04096427,  4.57797583,  8.41779199, -0.07240262]])

In [ ]:
b.dtype

dtype('float64')

In [ ]:
c=np.random.randint(1,81,(3,3))
c

array([[32, 72, 79],
       [69, 16, 42],
       [37, 45, 12]])

In [ ]:
c.ndim

2

In [ ]:
c.shape

(3, 3)

In [ ]:
c.dtype

dtype('int64')

In [ ]:
a=["mehmet"]
a

['mehmet']

In [ ]:
a[0]

'mehmet'

In [ ]:
type(a)

list

In [ ]:
type(a[0])

str

In [ ]:
c=np.random.randint(1,5,size=(18))
c

array([2, 2, 1, 4, 4, 3, 4, 4, 1, 1, 1, 2, 1, 2, 4, 3, 4, 4])

In [ ]:
c.reshape(6,3)

array([[2, 2, 1],
       [4, 4, 3],
       [4, 4, 1],
       [1, 1, 2],
       [1, 2, 4],
       [3, 4, 4]])

In [ ]:
c.reshape(-1,6)

array([[2, 2, 1, 4, 4, 3],
       [4, 4, 1, 1, 1, 2],
       [1, 2, 4, 3, 4, 4]])

In [ ]:
c.reshape(6,-1)

array([[2, 2, 1],
       [4, 4, 3],
       [4, 4, 1],
       [1, 1, 2],
       [1, 2, 4],
       [3, 4, 4]])

In [ ]:
x=np.random.randint(100,size=10)
x

array([31, 84, 61, 86, 35, 95, 97, 96, 33, 14])

In [ ]:
x[2]

61

In [ ]:
x[-2]

33

In [ ]:
s="aliahmet"

In [ ]:
s[2]

'i'

In [ ]:
s[::]

'aliahmet'

In [ ]:
s[:3]

'ali'

In [ ]:
s[::-1]

'temhaila'

In [ ]:
m=np.random.randint(10,size=(3,5))
m

array([[8, 7, 3, 4, 6],
       [3, 8, 3, 9, 3],
       [8, 1, 2, 6, 6]])

In [ ]:
m[2,3]

6

In [ ]:
m[1,3]

9

In [ ]:
m[1,3]=72

In [ ]:
m

array([[ 8,  7,  3,  4,  6],
       [ 3,  8,  3, 72,  3],
       [ 8,  1,  2,  6,  6]])

In [ ]:
m[:2,:]

array([[ 8,  7,  3,  4,  6],
       [ 3,  8,  3, 72,  3]])

In [ ]:
m[1:,3:]#72-3

array([[72,  3],
       [ 6,  6]])

In [ ]:
x=np.arange(0,50,5)
x

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
#fancy index
a=[0,2,4]
x[a]

array([ 0, 10, 20])

In [ ]:
y=np.array(range(21))
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [ ]:
for i in y:
  if i <10:
    print(i)

In [ ]:
y<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False])

In [ ]:
y[True]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20]])

In [ ]:
y[y<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y[y>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
y**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400])

In [ ]:
y-1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17, 18, 19])

In [ ]:
y.sum()

210

In [ ]:
y.mean()

10.0

In [ ]:
y.max()

20

In [ ]:
y.min()

0

In [ ]:
# 5x1+3x2=72
# 3x1+9x2=81

In [ ]:
a=np.array([[5,3],[3,9]])
b=np.array([72,81])

In [ ]:
a

array([[5, 3],
       [3, 9]])

In [ ]:
b

array([72, 81])

In [ ]:
xs=np.linalg.solve(a,b)
xs

array([11.25,  5.25])

In [ ]:
x1,x2=xs

In [ ]:
x1

11.25

In [ ]:
x2

5.25

#Pandas

In [1]:
import numpy as np
import pandas as pd 

ModuleNotFoundError: No module named 'pandas'

In [ ]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [ ]:
s=pd.Series([1,2,3,4,5,6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
s.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
s.dtype

dtype('int64')

In [ ]:
s.size

6

In [ ]:
s.ndim

1

In [ ]:
s.values

array([1, 2, 3, 4, 5, 6])

In [ ]:
s.head()

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
s.tail(2)

4    5
5    6
dtype: int64

In [ ]:
pd.DataFrame(np.random.rand(14,30))

0         1         2         3         4         5         6         7         8         9         10        11        12        13        14        15        16        17        18        19        20        21        22        23        24        25        26        27        28        29
0   0.648872  0.571549  0.284859  0.076755  0.609782  0.515434  0.967125  0.169606  0.018726  0.653279  0.037758  0.209084  0.157773  0.782346  0.612351  0.991496  0.627059  0.691711  0.147236  0.044458  0.145071  0.383902  0.954026  0.888674  0.066951  0.964257  0.314658  0.591299  0.781521  0.775050
1   0.605458  0.646037  0.937782  0.018927  0.624873  0.861138  0.756363  0.324784  0.602863  0.148382  0.271667  0.913953  0.696958  0.161981  0.363960  0.885495  0.116240  0.017103  0.235262  0.540759  0.130257  0.057350  0.948919  0.335161  0.804895  0.415592  0.248002  0.998769  0.102571  0.912249
2   0.601837  0.285512  0.291834  0.096255  0.207250  0.680942  0.067354  0.368243  0.740734  0.217498  0.918802  0.258225  0.998180  0.978793  0.327651  0.751549  0.007735  0.327961  0.732477  0.844598  0.001941  0.720202  0.030349  0.699087  0.980085  0.322107  0.535327  0.580333  0.765652  0.597758
3   0.141837  0.573885  0.618924  0.699309  0.077062  0.210771  0.195508  0.212766  0.699955  0.478989  0.133217  0.431620  0.631653  0.783580  0.000207  0.209718  0.564238  0.307507  0.498881  0.616961  0.614049  0.970421  0.513219  0.243537  0.245732  0.758395  0.314044  0.871017  0.330905  0.666472
4   0.534425  0.467516  0.603756  0.158348  0.219750  0.908814  0.238736  0.490507  0.236284  0.981146  0.176970  0.594370  0.280259  0.725277  0.155152  0.421338  0.421660  0.258655  0.519780  0.876937  0.444949  0.733096  0.171379  0.353923  0.026414  0.558891  0.489753  0.949845  0.089038  0.587050
5   0.232040  0.493763  0.854787  0.861733  0.473699  0.290226  0.748857  0.668872  0.963538  0.748877  0.058070  0.741235  0.283678  0.963415  0.000448  0.832061  0.817687  0.119183  0.582174  0.707376  0.102173  0.103282  0.143704  0.332487  0.712396  0.404217  0.779883  0.636251  0.769383  0.848427
6   0.611341  0.517341  0.559404  0.536362  0.479478  0.070210  0.095518  0.999339  0.654056  0.006065  0.187775  0.872572  0.246438  0.129709  0.718026  0.630053  0.947848  0.414842  0.444947  0.351754  0.743682  0.168284  0.306308  0.115015  0.846689  0.333931  0.989344  0.035768  0.030635  0.515609
7   0.968569  0.939217  0.000640  0.832535  0.360741  0.419981  0.029798  0.743250  0.132380  0.883302  0.339154  0.586883  0.940535  0.926885  0.184620  0.141375  0.443225  0.082421  0.694483  0.916671  0.115061  0.011598  0.845835  0.262421  0.212539  0.731088  0.042462  0.434102  0.244831  0.847540
8   0.817503  0.874327  0.351905  0.764052  0.576851  0.280879  0.474301  0.004486  0.549009  0.545024  0.653889  0.459964  0.801014  0.838470  0.076150  0.248146  0.171157  0.521841  0.855552  0.856346  0.171514  0.635365  0.860006  0.150455  0.546652  0.824766  0.318745  0.007092  0.964713  0.479048
9   0.607168  0.670543  0.819866  0.428493  0.328967  0.862025  0.504423  0.743579  0.476456  0.677229  0.127165  0.977817  0.534924  0.635412  0.565223  0.215893  0.082618  0.168235  0.860238  0.214546  0.179669  0.585724  0.529527  0.214368  0.734167  0.612352  0.912355  0.743267  0.400107  0.671430
10  0.898159  0.766531  0.769531  0.494059  0.961606  0.942299  0.597725  0.194152  0.536852  0.018891  0.902551  0.834502  0.274307  0.822223  0.754966  0.654358  0.714232  0.466469  0.328309  0.685839  0.128964  0.286071  0.514272  0.859298  0.435370  0.478405  0.276401  0.232386  0.449572  0.981988
11  0.247295  0.875438  0.490194  0.457717  0.513312  0.791590  0.596847  0.315801  0.008356  0.825785  0.183085  0.206835  0.164622  0.256594  0.028775  0.304247  0.096515  0.056489  0.749188  0.488049  0.554624  0.202227  0.523044  0.811588  0.932522  0.856681  0.163142  0.443342  0.387108  0.825672
12  0.508759  0.551177  0.657271  0.722192  0.286614  0.375213  0.58755

In [ ]:
pd.DataFrame(np.random.rand(5,8),columns=list("abcdefgh"))

a         b         c         d         e         f         g         h
0  0.612212  0.998932  0.958969  0.721901  0.725856  0.399561  0.584578  0.638434
1  0.333518  0.905552  0.908647  0.880608  0.830492  0.094170  0.064284  0.470571
2  0.285805  0.845204  0.934489  0.470142  0.237695  0.875130  0.709424  0.380216
3  0.713665  0.087508  0.317298  0.562778  0.479310  0.639724  0.814443  0.948331
4  0.251487  0.881797  0.772659  0.751989  0.957416  0.087951  0.629255  0.855601

In [ ]:
list("abcdefgh")

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

In [ ]:
import seaborn as sns

In [ ]:
df2=pd.read_csv("/content/Train.csv")# 
df2

Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility              Item_Type  Item_MRP Outlet_Identifier  Outlet_Establishment_Year Outlet_Size Outlet_Location_Type        Outlet_Type  Item_Outlet_Sales
0              FDA15        9.300          Low Fat         0.016047                  Dairy  249.8092            OUT049                       1999      Medium               Tier 1  Supermarket Type1          3735.1380
1              DRC01        5.920          Regular         0.019278            Soft Drinks   48.2692            OUT018                       2009      Medium               Tier 3  Supermarket Type2           443.4228
2              FDN15       17.500          Low Fat         0.016760                   Meat  141.6180            OUT049                       1999      Medium               Tier 1  Supermarket Type1          2097.2700
3              FDX07       19.200          Regular         0.000000  Fruits and Vegetables  182.0950            OUT010                       1998         NaN               Tier 3      Grocery Store           732.3800
4              NCD19        8.930          Low Fat         0.000000              Household   53.8614            OUT013                       1987        High               Tier 3  Supermarket Type1           994.7052
...              ...          ...              ...              ...                    ...       ...               ...                        ...         ...                  ...                ...                ...
8518           FDF22        6.865          Low Fat         0.056783            Snack Foods  214.5218            OUT013                       1987        High               Tier 3  Supermarket Type1          2778.3834
8519           FDS36        8.380          Regular         0.046982           Baking Goods  108.1570            OUT045                       2002         NaN               Tier 2  Supermarket Type1           549.2850
8520           NCJ29       10.600          Low Fat         0.035186     Health and Hygiene   85.1224            OUT035                       2004       Small               Tier 2  Supermarket Type1          1193.1136
8521           FDN46        7.210          Regular         0.145221            Snack Foods  103.1332            OUT018                       2009      Medium               Tier 3  Supermarket Type2          1845.5976
8522           DRG01       14.800          Low Fat         0.044878            Soft Drinks   75.4670            OUT046                       1997       Small               Tier 1  Supermarket Type1           765.6700

[8523 rows x 12 columns]

In [ ]:
df=sns.load_dataset("titanic")

In [ ]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0           0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
1           1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
2           1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3           1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4           0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
..        ...     ...     ...   ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
886         0       2    male  27.0      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
887         1       1  female  19.0      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
888         0       3  female   NaN      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
889         1       1    male  26.0      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
890         0       3    male  32.0      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
5         0       3    male   NaN      0      0   8.4583        Q   Third    man        True  NaN   Queenstown    no   True
6         0       1    male  54.0      0      0  51.8625        S   First    man        True    E  Southampton    no   True
7         0       3    male   2.0      3      1  21.0750        S   Third  child       False  NaN  Southampton    no  False
8         1       3  female  27.0      0      2  11.1333        S   Third  woman       False  NaN  Southampton   yes  False
9         1       2  female  14.0      1      0  30.0708        C  Second  child       False  NaN    Cherbourg   yes  False

In [ ]:
df.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class    who  adult_male deck  embark_town alive  alone
886         0       2    male  27.0      0      0  13.00        S  Second    man        True  NaN  Southampton    no   True
887         1       1  female  19.0      0      0  30.00        S   First  woman       False    B  Southampton   yes   True
888         0       3  female   NaN      1      2  23.45        S   Third  woman       False  NaN  Southampton    no  False
889         1       1    male  26.0      0      0  30.00        C   First    man        True    C    Cherbourg   yes   True
890         0       3    male  32.0      0      0   7.75        Q   Third    man        True  NaN   Queenstown    no   True

In [ ]:
df.shape #MxN

(891, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone'], dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [ ]:
df.describe().T

count       mean        std   min      25%      50%   75%       max
survived  891.0   0.383838   0.486592  0.00   0.0000   0.0000   1.0    1.0000
pclass    891.0   2.308642   0.836071  1.00   2.0000   3.0000   3.0    3.0000
age       714.0  29.699118  14.526497  0.42  20.1250  28.0000  38.0   80.0000
sibsp     891.0   0.523008   1.102743  0.00   0.0000   0.0000   1.0    8.0000
parch     891.0   0.381594   0.806057  0.00   0.0000   0.0000   0.0    6.0000
fare      891.0  32.204208  49.693429  0.00   7.9104  14.4542  31.0  512.3292

In [ ]:
df.isnull()

survived  pclass    sex    age  sibsp  parch   fare  embarked  class    who  adult_male   deck  embark_town  alive  alone
0       False   False  False  False  False  False  False     False  False  False       False   True        False  False  False
1       False   False  False  False  False  False  False     False  False  False       False  False        False  False  False
2       False   False  False  False  False  False  False     False  False  False       False   True        False  False  False
3       False   False  False  False  False  False  False     False  False  False       False  False        False  False  False
4       False   False  False  False  False  False  False     False  False  False       False   True        False  False  False
..        ...     ...    ...    ...    ...    ...    ...       ...    ...    ...         ...    ...          ...    ...    ...
886     False   False  False  False  False  False  False     False  False  False       False   True        False  False  False
887     False   False  False  False  False  False  False     False  False  False       False  False        False  False  False
888     False   False  False   True  False  False  False     False  False  False       False   True        False  False  False
889     False   False  False  False  False  False  False     False  False  False       False  False        False  False  False
890     False   False  False  False  False  False  False     False  False  False       False   True        False  False  False

[891 rows x 15 columns]

In [ ]:
df.isnull().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [ ]:
df.isnull().values.any()

True

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.head(10)

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
5         0       3    male   NaN      0      0   8.4583        Q   Third    man        True  NaN   Queenstown    no   True
6         0       1    male  54.0      0      0  51.8625        S   First    man        True    E  Southampton    no   True
7         0       3    male   2.0      3      1  21.0750        S   Third  child       False  NaN  Southampton    no  False
8         1       3  female  27.0      0      2  11.1333        S   Third  woman       False  NaN  Southampton   yes  False
9         1       2  female  14.0      1      0  30.0708        C  Second  child       False  NaN    Cherbourg   yes  False

In [ ]:
pd.set_option("display.max_columns",None)
pd.set_option("display.width",500)

In [ ]:
def check_df(df):
  print("**********head********************")
  print(df.head())
  print("**********tail********************")
  print(df.tail())
  print("**********info********************")
  print(df.info())
  print("**********columns*****************")
  print(df.columns)
  print("**********null_values*************")
  print(df.isnull().values.any())  
  print("**********shape*******************")
  print(df.shape)
  print("**********describe****************")
  print(df.describe().T)
  print("**********null_sum****************")
  print(df.isnull().sum())
  print("***********Corr*******************")
  print(df.corr())
  print("***********dtypes*****************")
  print(df.dtypes)
 
check_df(df)

**********head********************
   survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True
**********tail********************
     survived  pclass     sex   age  sibsp  parch   fare embarked   class    who  adult_male deck  embark_town alive  alone
886         0       2    male  27.0      0      0  13.00        S  S

In [ ]:
df2=sns.load_dataset("tips")

In [ ]:
check_df(df2)

**********head********************
   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4
**********tail********************
     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2
**********info********************
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True

In [ ]:
df.corr()

survived    pclass       age     sibsp     parch      fare  adult_male     alone
survived    1.000000 -0.338481 -0.077221 -0.035322  0.081629  0.257307   -0.557080 -0.203367
pclass     -0.338481  1.000000 -0.369226  0.083081  0.018443 -0.549500    0.094035  0.135207
age        -0.077221 -0.369226  1.000000 -0.308247 -0.189119  0.096067    0.280328  0.198270
sibsp      -0.035322  0.083081 -0.308247  1.000000  0.414838  0.159651   -0.253586 -0.584471
parch       0.081629  0.018443 -0.189119  0.414838  1.000000  0.216225   -0.349943 -0.583398
fare        0.257307 -0.549500  0.096067  0.159651  0.216225  1.000000   -0.182024 -0.271832
adult_male -0.557080  0.094035  0.280328 -0.253586 -0.349943 -0.182024    1.000000  0.404744
alone      -0.203367  0.135207  0.198270 -0.584471 -0.583398 -0.271832    0.404744  1.000000

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town', 'alive', 'alone'], dtype='object')

In [ ]:
[col.upper() if col.startswith("s") else col.lower() for col in df.columns ]

['SURVIVED',
 'pclass',
 'SEX',
 'age',
 'SIBSP',
 'parch',
 'fare',
 'embarked',
 'class',
 'who',
 'adult_male',
 'deck',
 'embark_town',
 'alive',
 'alone']

In [ ]:
df["sex"]

0        male
1      female
2      female
3      female
4        male
        ...  
886      male
887    female
888    female
889      male
890      male
Name: sex, Length: 891, dtype: object

In [ ]:
df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [ ]:
df["embarked"].value_counts()

S    644
C    168
Q     77
Name: embarked, dtype: int64

In [ ]:
[print(col+"\n",df[col].value_counts()) for col in df.columns]

survived
 0    549
1    342
Name: survived, dtype: int64
pclass
 3    491
1    216
2    184
Name: pclass, dtype: int64
sex
 male      577
female    314
Name: sex, dtype: int64
age
 24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: age, Length: 88, dtype: int64
sibsp
 0    608
1    209
2     28
4     18
3     16
8      7
5      5
Name: sibsp, dtype: int64
parch
 0    678
1    118
2     80
5      5
3      5
4      4
6      1
Name: parch, dtype: int64
fare
 8.0500     43
13.0000    42
7.8958     38
7.7500     34
26.0000    31
           ..
35.0000     1
28.5000     1
6.2375      1
14.0000     1
10.5167     1
Name: fare, Length: 248, dtype: int64
embarked
 S    644
C    168
Q     77
Name: embarked, dtype: int64
class
 Third     491
First     216
Second    184
Name: class, dtype: int64
who
 man      537
woman    271
child     83
Name: who, dtype: int64
adult_male
 True     537
False    354
Name: adult_ma

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [ ]:
df.sex.value_counts()# df["sex"].value_counts()

male      577
female    314
Name: sex, dtype: int64

In [ ]:
df.age.sum()

21205.17

### Pandasta secim islemleri

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True

In [ ]:
df[:14]

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0          0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
1          1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
2          1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3          1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4          0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
5          0       3    male   NaN      0      0   8.4583        Q   Third    man        True  NaN   Queenstown    no   True
6          0       1    male  54.0      0      0  51.8625        S   First    man        True    E  Southampton    no   True
7          0       3    male   2.0      3      1  21.0750        S   Third  child       False  NaN  Southampton    no  False
8          1       3  female  27.0      0      2  11.1333        S   Third  woman       False  NaN  Southampton   yes  False
9          1       2  female  14.0      1      0  30.0708        C  Second  child       False  NaN    Cherbourg   yes  False
10         1       3  female   4.0      1      1  16.7000        S   Third  child       False    G  Southampton   yes  False
11         1       1  female  58.0      0      0  26.5500        S   First  woman       False    C  Southampton   yes   True
12         0       3    male  20.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
13         0       3    male  39.0      1      5  31.2750        S   Third    man        True  NaN  Southampton    no  False

In [ ]:
df.drop(2,axis=0).head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True
5         0       3    male   NaN      0      0   8.4583        Q  Third    man        True  NaN   Queenstown    no   True

In [ ]:
#axis=0 satir,index
# axis=1 sütün,column

In [ ]:
indexes=[1,7,2]
df.drop(indexes,axis=0)

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0           0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
3           1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4           0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
5           0       3    male   NaN      0      0   8.4583        Q   Third    man        True  NaN   Queenstown    no   True
6           0       1    male  54.0      0      0  51.8625        S   First    man        True    E  Southampton    no   True
..        ...     ...     ...   ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
886         0       2    male  27.0      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
887         1       1  female  19.0      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
888         0       3  female   NaN      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
889         1       1    male  26.0      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
890         0       3    male  32.0      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[888 rows x 15 columns]

In [ ]:
df.index=df["age"]
df


survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
age                                                                                                                           
22.0         0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
38.0         1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
26.0         1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
35.0         1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
35.0         0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
...        ...     ...     ...   ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
27.0         0       2    male  27.0      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
19.0         1       1  female  19.0      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
NaN          0       3  female   NaN      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
26.0         1       1    male  26.0      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
32.0         0       3    male  32.0      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
age                                                                                                                           
22.0         0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
38.0         1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
26.0         1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
35.0         1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
35.0         0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
...        ...     ...     ...   ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
27.0         0       2    male  27.0      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
19.0         1       1  female  19.0      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
NaN          0       3  female   NaN      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
26.0         1       1    male  26.0      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
32.0         0       3    male  32.0      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
df.index

Float64Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,
              ...
              33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0], dtype='float64', name='age', length=891)

In [ ]:
df2=df.drop("age",axis=1)
df2

survived  pclass     sex  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
age                                                                                                                     
22.0         0       3    male      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
38.0         1       1  female      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
26.0         1       3  female      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
35.0         1       1  female      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
35.0         0       3    male      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
...        ...     ...     ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
27.0         0       2    male      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
19.0         1       1  female      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
NaN          0       3  female      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
26.0         1       1    male      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
32.0         0       3    male      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 14 columns]

In [ ]:
df.drop("age",axis=1,inplace=True)

In [ ]:
df

survived  pclass     sex  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
age                                                                                                                     
22.0         0       3    male      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
38.0         1       1  female      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
26.0         1       3  female      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
35.0         1       1  female      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
35.0         0       3    male      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
...        ...     ...     ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
27.0         0       2    male      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
19.0         1       1  female      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
NaN          0       3  female      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
26.0         1       1    male      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
32.0         0       3    male      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 14 columns]

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

age  survived  pclass     sex  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0    22.0         0       3    male      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
1    38.0         1       1  female      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
2    26.0         1       3  female      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3    35.0         1       1  female      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4    35.0         0       3    male      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
..    ...       ...     ...     ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
886  27.0         0       2    male      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
887  19.0         1       1  female      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
888   NaN         0       3  female      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
889  26.0         1       1    male      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
890  32.0         0       3    male      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
import pandas as pd
import seaborn as sns
pd.set_option("display.max_columns",None)
df=sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True

In [ ]:
"age" in df

True

In [ ]:
type(df["age"])

pandas.core.series.Series

In [ ]:
type(df[["age"]])

pandas.core.frame.DataFrame

In [ ]:
df[["age","sex","class"]]

age     sex   class
0    22.0    male   Third
1    38.0  female   First
2    26.0  female   Third
3    35.0  female   First
4    35.0    male   Third
..    ...     ...     ...
886  27.0    male  Second
887  19.0  female   First
888   NaN  female   Third
889  26.0    male   First
890  32.0    male   Third

[891 rows x 3 columns]

In [ ]:
col_names=["sex","pclass","alive"]
df[col_names].head()

sex  pclass alive
0    male       3    no
1  female       1   yes
2  female       3   yes
3  female       1   yes
4    male       3    no

In [ ]:
df["batman"]=df["age"]*3
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone  batman
0           0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False    66.0
1           1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False   114.0
2           1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True    78.0
3           1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False   105.0
4           0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True   105.0
..        ...     ...     ...   ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...     ...
886         0       2    male  27.0      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True    81.0
887         1       1  female  19.0      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True    57.0
888         0       3  female   NaN      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False     NaN
889         1       1    male  26.0      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True    78.0
890         0       3    male  32.0      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True    96.0

[891 rows x 16 columns]

In [ ]:
df["batman2"]=df["age"]*4

In [ ]:
df.drop(["batman","batman2"],axis=1,inplace=True)

In [ ]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0           0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
1           1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
2           1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3           1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4           0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
..        ...     ...     ...   ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
886         0       2    male  27.0      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
887         1       1  female  19.0      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
888         0       3  female   NaN      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
889         1       1    male  26.0      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
890         0       3    male  32.0      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
df.loc[:4,["age","class"]]

age  class
0  22.0  Third
1  38.0  First
2  26.0  Third
3  35.0  First
4  35.0  Third

In [ ]:
df["batman"]=df["age"]*3
df["batman2"]=df["age"]*4

In [ ]:
df.drop(df.loc[:,df.columns.str.contains("batman")],axis=1, inplace=True)

In [ ]:
df

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
0           0       3    male  22.0      1      0   7.2500        S   Third    man        True  NaN  Southampton    no  False
1           1       1  female  38.0      1      0  71.2833        C   First  woman       False    C    Cherbourg   yes  False
2           1       3  female  26.0      0      0   7.9250        S   Third  woman       False  NaN  Southampton   yes   True
3           1       1  female  35.0      1      0  53.1000        S   First  woman       False    C  Southampton   yes  False
4           0       3    male  35.0      0      0   8.0500        S   Third    man        True  NaN  Southampton    no   True
..        ...     ...     ...   ...    ...    ...      ...      ...     ...    ...         ...  ...          ...   ...    ...
886         0       2    male  27.0      0      0  13.0000        S  Second    man        True  NaN  Southampton    no   True
887         1       1  female  19.0      0      0  30.0000        S   First  woman       False    B  Southampton   yes   True
888         0       3  female   NaN      1      2  23.4500        S   Third  woman       False  NaN  Southampton    no  False
889         1       1    male  26.0      0      0  30.0000        C   First    man        True    C    Cherbourg   yes   True
890         0       3    male  32.0      0      0   7.7500        Q   Third    man        True  NaN   Queenstown    no   True

[891 rows x 15 columns]

In [ ]:
df.loc[:,df.columns.str.contains("s")]

survived  pclass     sex  sibsp   class
0           0       3    male      1   Third
1           1       1  female      1   First
2           1       3  female      0   Third
3           1       1  female      1   First
4           0       3    male      0   Third
..        ...     ...     ...    ...     ...
886         0       2    male      0  Second
887         1       1  female      0   First
888         0       3  female      1   Third
889         1       1    male      0   First
890         0       3    male      0   Third

[891 rows x 5 columns]

In [ ]:
df.loc[:,~df.columns.str.contains("s")]

age  parch     fare embarked    who  adult_male deck  embark_town alive  alone
0    22.0      0   7.2500        S    man        True  NaN  Southampton    no  False
1    38.0      0  71.2833        C  woman       False    C    Cherbourg   yes  False
2    26.0      0   7.9250        S  woman       False  NaN  Southampton   yes   True
3    35.0      0  53.1000        S  woman       False    C  Southampton   yes  False
4    35.0      0   8.0500        S    man        True  NaN  Southampton    no   True
..    ...    ...      ...      ...    ...         ...  ...          ...   ...    ...
886  27.0      0  13.0000        S    man        True  NaN  Southampton    no   True
887  19.0      0  30.0000        S  woman       False    B  Southampton   yes   True
888   NaN      2  23.4500        S  woman       False  NaN  Southampton    no  False
889  26.0      0  30.0000        C    man        True    C    Cherbourg   yes   True
890  32.0      0   7.7500        Q    man        True  NaN   Queenstown    no   True

[891 rows x 10 columns]

In [ ]:
df.iloc[0:3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True

In [ ]:
df.loc[0:3]

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False

In [ ]:
df[df["age"]>72]

survived  pclass   sex   age  sibsp  parch    fare embarked  class  who  adult_male deck  embark_town alive  alone
630         1       1  male  80.0      0      0  30.000        S  First  man        True    A  Southampton   yes   True
851         0       3  male  74.0      0      0   7.775        S  Third  man        True  NaN  Southampton    no   True

In [ ]:
df[df["age"]>72].count()

survived       2
pclass         2
sex            2
age            2
sibsp          2
parch          2
fare           2
embarked       2
class          2
who            2
adult_male     2
deck           1
embark_town    2
alive          2
alone          2
dtype: int64

In [ ]:
df[df["age"]>72]["survived"].count()

2

In [ ]:
df.loc[df["age"]>50,["age","class"]]

age   class
6    54.0   First
11   58.0   First
15   55.0  Second
33   66.0  Second
54   65.0   First
..    ...     ...
820  52.0   First
829  62.0   First
851  74.0   Third
857  51.0   First
879  56.0   First

[64 rows x 2 columns]

In [ ]:
df[(df["age"]>50) & (df["sex"]=="male")]

survived  pclass   sex   age  sibsp  parch      fare embarked   class  who  adult_male deck  embark_town alive  alone
6           0       1  male  54.0      0      0   51.8625        S   First  man        True    E  Southampton    no   True
33          0       2  male  66.0      0      0   10.5000        S  Second  man        True  NaN  Southampton    no   True
54          0       1  male  65.0      0      1   61.9792        C   First  man        True    B    Cherbourg    no  False
94          0       3  male  59.0      0      0    7.2500        S   Third  man        True  NaN  Southampton    no   True
96          0       1  male  71.0      0      0   34.6542        C   First  man        True    A    Cherbourg    no   True
116         0       3  male  70.5      0      0    7.7500        Q   Third  man        True  NaN   Queenstown    no   True
124         0       1  male  54.0      0      1   77.2875        S   First  man        True    D  Southampton    no  False
150         0       2  male  51.0      0      0   12.5250        S  Second  man        True  NaN  Southampton    no   True
152         0       3  male  55.5      0      0    8.0500        S   Third  man        True  NaN  Southampton    no   True
155         0       1  male  51.0      0      1   61.3792        C   First  man        True  NaN    Cherbourg    no  False
170         0       1  male  61.0      0      0   33.5000        S   First  man        True    B  Southampton    no   True
174         0       1  male  56.0      0      0   30.6958        C   First  man        True    A    Cherbourg    no   True
222         0       3  male  51.0      0      0    8.0500        S   Third  man        True  NaN  Southampton    no   True
232         0       2  male  59.0      0      0   13.5000        S  Second  man        True  NaN  Southampton    no   True
249         0       2  male  54.0      1      0   26.0000        S  Second  man        True  NaN  Southampton    no  False
252         0       1  male  62.0      0      0   26.5500        S   First  man        True    C  Southampton    no   True
262         0       1  male  52.0      1      1   79.6500        S   First  man        True    E  Southampton    no  False
280         0       3  male  65.0      0      0    7.7500        Q   Third  man        True  NaN   Queenstown    no   True
317         0       2  male  54.0      0      0   14.0000        S  Second  man        True  NaN  Southampton    no   True
326         0       3  male  61.0      0      0    6.2375        S   Third  man        True  NaN  Southampton    no   True
406         0       3  male  51.0      0      0    7.7500        S   Third  man        True  NaN  Southampton    no   True
438         0       1  male  64.0      1      4  263.0000        S   First  man        True    C  Southampton    no  False
449         1       1  male  52.0      0      0   30.5000        S   First  man        True    C  Southampton   yes   True
456         0       1  male  65.0      0      0   26.5500        S   First  man        True    E  Southampton    no   True
467         0       1  male  56.0      0      0   26.5500        S   First  man        True  NaN  Southampton    no   True
487         0       1  male  58.0      0      0   29.7000        C   First  man        True    B    Cherbourg    no   True
492         0       1  male  55.0      0      0   30.5000        S   First  man        True    C  Southampton    no   True
493         0       1  male  71.0      0      0   49.5042        C   First  man        True  NaN    Cherbourg    no   True
545         0       1  male  64.0      0      0   26.0000        S   First  man        True  NaN  Southampton    no   True
555         0       1  male  62.0      0      0   26.5500        S   First  man        True  NaN  Southampton    no   True
570         1       2  male  62.0      0      0   10.5000        S  Second  man        True  NaN  Southampton   yes   True
582         0       2  male  54.0      0      0   26.0000        S  S

In [ ]:
df.age.sum()

21205.17

In [ ]:
df.age.mean()

29.69911764705882

In [ ]:
df.age.min()

0.42

In [ ]:
df.age.max()

80.0

In [ ]:
df.nlargest(5,"age")

survived  pclass   sex   age  sibsp  parch     fare embarked  class  who  adult_male deck  embark_town alive  alone
630         1       1  male  80.0      0      0  30.0000        S  First  man        True    A  Southampton   yes   True
851         0       3  male  74.0      0      0   7.7750        S  Third  man        True  NaN  Southampton    no   True
96          0       1  male  71.0      0      0  34.6542        C  First  man        True    A    Cherbourg    no   True
493         0       1  male  71.0      0      0  49.5042        C  First  man        True  NaN    Cherbourg    no   True
116         0       3  male  70.5      0      0   7.7500        Q  Third  man        True  NaN   Queenstown    no   True

In [ ]:
df.nsmallest(5,"age")

survived  pclass     sex   age  sibsp  parch     fare embarked   class    who  adult_male deck  embark_town alive  alone
803         1       3    male  0.42      0      1   8.5167        C   Third  child       False  NaN    Cherbourg   yes  False
755         1       2    male  0.67      1      1  14.5000        S  Second  child       False  NaN  Southampton   yes  False
469         1       3  female  0.75      2      1  19.2583        C   Third  child       False  NaN    Cherbourg   yes  False
644         1       3  female  0.75      2      1  19.2583        C   Third  child       False  NaN    Cherbourg   yes  False
78          1       2    male  0.83      0      2  29.0000        S  Second  child       False  NaN  Southampton   yes  False

In [ ]:
df.head(10).style.bar(color="yellow")

In [ ]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True

In [ ]:
df.groupby("pclass")["survived"].mean()

pclass
1    0.629630
2    0.472826
3    0.242363
Name: survived, dtype: float64

In [ ]:
df.groupby("embark_town")["age"].mean()

embark_town
Cherbourg      30.814769
Queenstown     28.089286
Southampton    29.445397
Name: age, dtype: float64

In [ ]:
df.groupby("embark_town")["survived"].count()

embark_town
Cherbourg      168
Queenstown      77
Southampton    644
Name: survived, dtype: int64

In [ ]:
df.groupby(["embark_town","age","sex"])["survived"].count()

embark_town  age    sex   
Cherbourg    0.42   male      1
             0.75   female    2
             1.00   female    1
                    male      1
             3.00   female    1
                             ..
Southampton  65.00  male      1
             66.00  male      1
             70.00  male      2
             74.00  male      1
             80.00  male      1
Name: survived, Length: 236, dtype: int64

In [ ]:
df.groupby("sex").agg({"age":"mean"})

age
sex              
female  27.915709
male    30.726645

In [ ]:
df.groupby("sex").agg({"age":["min","mean","max"]})

age                 
         min       mean   max
sex                          
female  0.75  27.915709  63.0
male    0.42  30.726645  80.0

In [ ]:
df.groupby("sex").agg({"age":"mean",
                       "survived":"mean"})

age  survived
sex                        
female  27.915709  0.742038
male    30.726645  0.188908

In [ ]:
df.groupby(["sex","class"]).agg({"age":"mean",
                       "survived":"mean"})

age  survived
sex    class                      
female First   34.611765  0.968085
       Second  28.722973  0.921053
       Third   21.750000  0.500000
male   First   41.281386  0.368852
       Second  30.740707  0.157407
       Third   26.507589  0.135447

In [ ]:
df.groupby(["sex","class"]).agg({"age":"mean",
                       "survived":["mean","count"]})

age  survived      
                    mean      mean count
sex    class                            
female First   34.611765  0.968085    94
       Second  28.722973  0.921053    76
       Third   21.750000  0.500000   144
male   First   41.281386  0.368852   122
       Second  30.740707  0.157407   108
       Third   26.507589  0.135447   347

In [ ]:
df.pivot_table("survived","sex","embarked")

embarked         C         Q         S
sex                                   
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.dropna()

survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
1           1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
3           1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
6           0       1    male  54.0      0      0  51.8625        S  First    man        True    E  Southampton    no   True
10          1       3  female   4.0      1      1  16.7000        S  Third  child       False    G  Southampton   yes  False
11          1       1  female  58.0      0      0  26.5500        S  First  woman       False    C  Southampton   yes   True
..        ...     ...     ...   ...    ...    ...      ...      ...    ...    ...         ...  ...          ...   ...    ...
871         1       1  female  47.0      1      1  52.5542        S  First  woman       False    D  Southampton   yes  False
872         0       1    male  33.0      0      0   5.0000        S  First    man        True    B  Southampton    no   True
879         1       1  female  56.0      0      1  83.1583        C  First  woman       False    C    Cherbourg   yes  False
887         1       1  female  19.0      0      0  30.0000        S  First  woman       False    B  Southampton   yes   True
889         1       1    male  26.0      0      0  30.0000        C  First    man        True    C    Cherbourg   yes   True

[182 rows x 15 columns]

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.age.mean()#35

29.69911764705882

In [ ]:
df["age"]=df["age"].fillna(35)

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64