In [4]:
import pandas as pd

In [1]:
nt = [30, 80, 40, 90, 60, 45, 95, 75, 55, 100, 65, 85]

In [2]:
aralık = [20, 40, 60, 80, 100]

In [5]:
puan = pd.cut(nt, aralık)
puan

# nt değişkenindeki her bir değerin hangi aralığa ait olduğunu gösteriyor.

[(20, 40], (60, 80], (20, 40], (80, 100], (40, 60], ..., (60, 80], (40, 60], (80, 100], (60, 80], (80, 100]]
Length: 12
Categories (4, interval[int64, right]): [(20, 40] < (40, 60] < (60, 80] < (80, 100]]

In [7]:
puan.codes

# aralık değişkenine göre hangi aralıkta olduğunu bize söylüyor.
# 20-40 arası 0 , 40-60 arası 1 ... gibi

array([0, 2, 0, 3, 1, 1, 3, 2, 1, 3, 2, 3], dtype=int8)

In [8]:
puan.categories

# veri seti için belirlenmiş kategorileri gözlemleyebiliriz.

IntervalIndex([(20, 40], (40, 60], (60, 80], (80, 100]], dtype='interval[int64, right]')

In [9]:
pd.value_counts(puan)

# kategorilerde kaç adet veri olduğunu value_counts() methoduyla öğrenebiliyoruz.

(80, 100]    4
(40, 60]     3
(60, 80]     3
(20, 40]     2
dtype: int64

In [10]:
puan = pd.cut(nt, aralık, right= False)
puan

# right= parametresine False değeri girersek aralığın kapalı parantez olduğu kısmı değiştirebiliyoruz.

[[20, 40), [80, 100), [40, 60), [80, 100), [60, 80), ..., [60.0, 80.0), [40.0, 60.0), NaN, [60.0, 80.0), [80.0, 100.0)]
Length: 12
Categories (4, interval[int64, left]): [[20, 40) < [40, 60) < [60, 80) < [80, 100)]

In [11]:
isim = ["düşük", "orta", "yüksek", "tavan"]

In [12]:
pd.cut(nt, aralık, labels= isim)

# labels= parametresiyle aralıklara isim verebiliyoruz.

['düşük', 'yüksek', 'düşük', 'tavan', 'orta', ..., 'yüksek', 'orta', 'tavan', 'yüksek', 'tavan']
Length: 12
Categories (4, object): ['düşük' < 'orta' < 'yüksek' < 'tavan']

In [13]:
pd.cut(nt, 10)

# nt verisi için 10 adet aralık belirlemiş olduk.

[(29.93, 37.0], (79.0, 86.0], (37.0, 44.0], (86.0, 93.0], (58.0, 65.0], ..., (72.0, 79.0], (51.0, 58.0], (93.0, 100.0], (58.0, 65.0], (79.0, 86.0]]
Length: 12
Categories (10, interval[float64, right]): [(29.93, 37.0] < (37.0, 44.0] < (44.0, 51.0] < (51.0, 58.0] ... (72.0, 79.0] < (79.0, 86.0] < (86.0, 93.0] < (93.0, 100.0]]

In [14]:
import numpy as np

veri = np.random.randn(100)

In [16]:
x = pd.qcut(veri, 4)
x

# veri değişkenimizin değerlerini 4 çeyreğe hale getirdik.

[(-2.078, -0.629], (0.536, 3.151], (-2.078, -0.629], (0.536, 3.151], (0.536, 3.151], ..., (-0.629, 0.013], (0.536, 3.151], (-2.078, -0.629], (-0.629, 0.013], (0.013, 0.536]]
Length: 100
Categories (4, interval[float64, right]): [(-2.078, -0.629] < (-0.629, 0.013] < (0.013, 0.536] < (0.536, 3.151]]

In [17]:
pd.value_counts(x)

# gördüğünüz gibi her birinde 25 eleman bulunuyor.

(-2.078, -0.629]    25
(-0.629, 0.013]     25
(0.013, 0.536]      25
(0.536, 3.151]      25
dtype: int64

In [18]:
veri = pd.DataFrame(np.random.randn(1000, 4))

In [19]:
veri.head()

# ilk 5 satırını görüntüledik.

0         1         2         3
0 -1.076104 -0.522739 -0.287500  0.003194
1  2.471688 -1.218818 -1.611362  0.490224
2  1.533134  1.390479  0.135090  0.188698
3  0.125896 -0.945204  1.167990  0.985661
4 -0.068464 -1.010397 -0.720832 -0.627621

In [20]:
veri.describe()

# her sütun için özet istatistikleri alabiliyoruz.

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.061716    -0.043724     0.014904    -0.008411
std       0.996460     0.987662     1.000666     0.990754
min      -3.439575    -3.105509    -2.971773    -2.996200
25%      -0.650160    -0.724426    -0.640575    -0.677215
50%       0.046873    -0.051776     0.048567     0.000744
75%       0.727356     0.661967     0.654472     0.687862
max       3.384327     3.121725     3.858390     2.981912

In [21]:
sütun = veri[1]

In [22]:
sütun[np.abs(sütun) > 3]

# 1. sütunda mutlak değeri 3'ü geçen sayıları aldık.

786   -3.105509
954    3.121725
Name: 1, dtype: float64

In [28]:
veri[(np.abs(veri) > 3).any(1)]

# Bütun sütunlarda mutlak değeri 3 ü geçen satırları yazdırdık.

C:\Users\Fallrytme\AppData\Local\Temp\ipykernel_11680\1996238441.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.any and Series.any will be keyword-only.
  veri[(np.abs(veri) > 3).any(1)]


0         1         2         3
206  3.032911  1.309933 -0.159491  0.944719
545  3.302046  0.820953 -0.655697 -2.093315
637 -3.439575  1.590673 -0.053203 -0.570993
646  0.047496  0.524806  3.475955  1.753737
786 -0.473539 -3.105509 -0.380747  0.921823
881  3.384327 -0.909315 -2.510891  1.329257
916  0.661686  1.142954  3.858390 -0.303516
954 -1.167497  3.121725  1.155598  0.335591

In [29]:
np.sign(veri).head()

# verilerin negatif mi pozitif mi olduğuna baktık. 
# - değer gelenler negatif diğerleri pozitif oluyor.

0    1    2    3
0 -1.0 -1.0 -1.0  1.0
1  1.0 -1.0 -1.0  1.0
2  1.0  1.0  1.0  1.0
3  1.0 -1.0  1.0  1.0
4 -1.0 -1.0 -1.0 -1.0

In [30]:
veri = pd.DataFrame(np.arange(12).reshape(4, 3))
veri

# dataframe tipinde veri oluşturduk.

0   1   2
0  0   1   2
1  3   4   5
2  6   7   8
3  9  10  11

In [35]:
sıra = np.random.permutation(4)
sıra

# numpy tipinde veri oluşturduk.

array([1, 2, 0, 3])

In [36]:
veri.take(sıra)

# veri değişkenindeki satır değerlerinin sırayla aynı sırada olduğunu görebilirsiniz.

0   1   2
1  3   4   5
2  6   7   8
0  0   1   2
3  9  10  11

In [37]:
veri.sample()

# rastgele bir satır seçilir.

0   1   2
3  9  10  11

In [38]:
veri.sample()

# gördüğünüz gibi.

0  1  2
2  6  7  8

In [39]:
veri.sample(2)

# rastgele seçilecek satır sayısını da belirleyebiliriz.

0  1  2
2  6  7  8
1  3  4  5

In [41]:
veri = pd.DataFrame({"harf": ["c", "b", "a", "b", "b", "a"], 
"sayı": range(6)})
veri

# veri değişkeninde dataframe veri setimizi oluşturduk.

harf  sayı
0    c     0
1    b     1
2    a     2
3    b     3
4    b     4
5    a     5

In [42]:
pd.get_dummies(veri["harf"])

# satırlarda hangi sütunda değer varsa bize 1 döndürülür.

a  b  c
0  0  0  1
1  0  1  0
2  1  0  0
3  0  1  0
4  0  1  0
5  1  0  0

In [44]:
veri = np.random.randn(10)
veri

array([-1.3483017 ,  2.73960784,  1.42858586,  1.19608971,  0.41718686,
        0.77876928,  1.84189035,  0.34171126,  0.35122263, -1.20084511])

In [45]:
pd.get_dummies(pd.cut(veri, 4))

# Önce veri değişkenimizi 4 çeyreğe böldük
# Sonra hangi aralıklarda değerimiz olduğuna get_dummies() methoduyla baktık.

(-1.352, -0.326]  (-0.326, 0.696]  (0.696, 1.718]  (1.718, 2.74]
0                 1                0               0              0
1                 0                0               0              1
2                 0                0               1              0
3                 0                0               1              0
4                 0                1               0              0
5                 0                0               1              0
6                 0                0               0              1
7                 0                1               0              0
8                 0                1               0              0
9                 1                0               0              0